name: graphql_generator3
version: 7.0.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server2.
publish_to: none
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  analyzer: ^7.0.0
  angel3_model: ^8.3.1
  angel3_serialize_generator: ^8.5.0
  graphql_schema2: ^6.2.0
  build: ^2.4.0
  build_config: ^1.1.0
  json_annotation: ^4.9.0
  code_builder: ^4.5.0
  recase: ^4.1.0
  source_gen: ^2.0.0
  collection: ^1.17.0
  graphql_annotation3:
    git: https://github.com/raphrmx/graphql_annotation3.git
dev_dependencies:
  build_runner: ^2.4.0
  lints: ^5.0.0
# dependency_overrides:
#   graphql_schema2:
#     path: ../graphql_schema


