name: graphql_generator3
version: 3.0.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server2.
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  analyzer: ^7.7.1
  angel3_model: ^8.4.0
  angel3_serialize_generator: ^8.6.0
  graphql_schema2: ^6.4.0
  build: ^3.1.0
  build_config: ^1.2.0
  json_annotation: ^4.9.0
  code_builder: ^4.11.0
  recase: ^4.1.0
  source_gen: ^3.1.0
  collection: ^1.19.1
  graphql_annotation3:
    git: https://github.com/raphrmx/graphql_annotation3.git

dev_dependencies:
  build_runner: ^2.7.1
  lints: ^6.0.0

dependency_overrides:
  graphql_annotation3:
    path: ../graphql_annotation3


